### ISSUE TITLE
機密情報がmasterにcommitされている

### ISSUE THREAD

**Issue by YuMuuu** [serviver-agent/git-practice-area#2]
（仮想的な課題なので実際には機密情報ではないが）commitされてしまっている

https://github.com/serviver-agent/git-practice-area/commit/e4369801e69f64b499318ed01cf3a7cb408acb76

**Comment by maconaco** [comment]
# Discordで話したこと
member: curelemonade, macololidoll

## 現状整理
### 前提: 何が問題か
最新の`origin/main`ブランチに変更したファイルがなくても
過去のコミットにあると`checkout`してみれてしまう
### issueが建てられる
- 機密情報はmasterにcommitされている
### mainにmergeされたcommitを修正しましょう
- 自分が今から作業するよりも前の(歴史的にみて)ブランチに対するコミットの修正をしなければならない
- 一般的には、`git rebase`コマンドは現在自分がいるブランチかつ、そこでのコミットに対してしか修正ができない
- merge済のブランチや枝分かれ前の(歴史的にみて)ブランチを修正する場合は`git rebase -i --root`
 `--root    rebase all reachable commits up to the root(s)`

### 手順1: rebaseで頑張る方法
1. `$ git rebase -i --root`
2. `$ git rm env`
3. `$ git rebase --continue`
4. `Successfully rebased and updated refs/heads/delete-env-file.`

### 手順2: 最強のオプション filter-branch
- `--tree-filter` オプションは、プロジェクトの各チェックアウトに対して指定したコマンドを実行し、結果を再コミットします
1. `git filter-branch --tree-filter 'rm -f env' HEAD`

### 二度と同じようなことが起きぬように対策するなら？
- `.gitignore`に`env`を追加する
