### ISSUE TITLE
ピザが冷蔵庫に入らない

### ISSUE THREAD

**Issue by KazuyaMiyashita** [serviver-agent/git-practice-area#7]
ピザハットでMサイズのピザを2枚注文した。食べ残しの2箱を冷蔵庫に入れたいが、冷蔵庫の奥行きが足りず入らない。

**Comment by maconaco** [comment]
ピザは何切れ残っていますか？
箱からは出せますか？

まるまる残っている、もしくは箱から出せない場合は、もうひとつピザ専用の冷蔵庫を買うことをオススメします。

2枚のピザって思ったより食べれないですよねw
私も3枚頼んで後悔したことがありますw
ピザの居場所が見つかることを祈っています。

**Comment by KazuyaMiyashita** [comment]
元々8切が2枚で、4切と8切残っています。
人見知りな性格なのか、呼びかけても、箱から出てくる様子がありません。
でも、美味しかったですよ😀

**Comment by aoiroaoino** [comment]
ちなみに私は寿司を食べました。美味しかったです 🍣 

<img width="294" alt="スクリーンショット 2020-11-25 20 48 06" src="https://user-images.githubusercontent.com/2589034/102381726-eaeb3380-400c-11eb-8e35-4fd9d6544527.png">
